var Pta=Pta||{};
Pta.listeners={initialize:function(a){a=document.getElementById(a);Pta.listeners.setTabs(a);a.style.tabSize=4;Pta.listeners.setIndent(a);Pta.listeners.setJoinLines(a);Pta.listeners.setMatching(a);Pta.listeners.setDupChr(a);Pta.listeners.setZen(a);Pta.listeners.setLineNbr(a)},setTabs:function(a){a.addEventListener("keydown",function(b){if(9===b.keyCode&&!b.shiftKey){b.preventDefault();var e,d,f,g;f=a.selectionStart;g=a.selectionEnd;d=a.value;if(f===g)a.value=d.slice(0,f)+"\t"+d.slice(g),a.selectionStart=
f+1,a.selectionEnd=f+1;else{b=d.slice(f,g);var c;e=b;var h=0;for(c=0;c<e.length;c+=1)"\n"===e.charAt(c)&&(h+=1);c=h;if(10!==d.charCodeAt(g-1))for(e=b.length;;){c=a.selectionEnd;f=d.indexOf(b,c);g=f+e;if(0<=f)a.selectionStart=f,a.selectionEnd=g;else if(0<c){a.selectionStart=0;a.selectionEnd=0;continue}return}b=b.replace(/\s+$/g,"");b=b.replace(RegExp("\n","g"),"\n\t");e=d.slice(0,f);d=d.slice(g);a.value=e+"\t"+b+"\n"+d;a.selectionStart=f;a.selectionEnd=g+c}}});a.addEventListener("keydown",function(b){if(9===
b.keyCode&&b.shiftKey){b.preventDefault();var e,d,f;b=a.selectionStart;f=a.selectionEnd;d=a.value;if(b===f)e=d.slice(0,b-1),d=d.slice(b),a.value=e+d,a.selectionStart=b-1,a.selectionEnd=b-1;else{var g=d.slice(b,f),c;e=g;var h=0;for(c=0;c<e.length;c+=1)"\n"===e.charAt(c)&&(h+=1);c=h;32<g.charCodeAt(0)||(g=g.replace(RegExp("\n\t","g"),"\n"),e=d.slice(0,b),d=d.slice(f),a.value=e+g.slice(1)+d,a.selectionStart=b,a.selectionEnd=f-c)}}})},setJoinLines:function(a){a.addEventListener("keydown",function(b){if("t"===
String.fromCharCode(b.which).toLowerCase()&&b.altKey){b.preventDefault();var e,d,f,g;d=a.selectionStart;e=a.selectionEnd;f=a.value;g=f.slice(d,e);""===g?alert("No Lines Selected to Join"):(b=f.slice(0,d),e=f.slice(e),g=g.replace(/\n/g,""),a.value=b+g+e,a.selectionEnd=d)}})},setIndent:function(a){a.addEventListener("keydown",function(b){if(13===b.keyCode&&!b.ctrlKey){b.preventDefault();var e,d,f=a.value,g=a.selectionStart,c=a.selectionEnd;for(b=g-1;0<b&&10!==f.charCodeAt(b);--b);e=String.fromCharCode(10);
0<b&&(b+=1);for(d=f.charCodeAt(b);32===d||9===d;)e+=String.fromCharCode(d),b+=1,d=f.charCodeAt(b);a.value=f.slice(0,g)+e+f.slice(c);a.selectionStart=g+e.length;a.selectionEnd=g+e.length}})},setMatching:function(a){function b(){var f=a.value,b=a.selectionStart,c=f.charAt(b);if(0>"{(".indexOf(c)&&(--b,c=f.charAt(b),0>"})".indexOf(c)))return;"}"===c?e("}","{",b):"{"===c?d("{","}",b):")"===c?e(")","(",b):"("===c&&d("(",")",b)}function e(d,b,c){var f,e=0,g=a.value;for(--c;0<=c;--c)if(f=g.charAt(c),f===
b)if(0===e){a.selectionStart=c;break}else--e;else f===d&&(e+=1);0>c&&alert("Match not found")}function d(d,b,c){var f,e,g=0,m=a.value;e=m.length;for(c+=1;c<e;c+=1)if(f=m.charAt(c),f===b)if(0===g){a.selectionEnd=c+1;break}else--g;else f===d&&(g+=1);c>=e&&alert("Match not found")}a.addEventListener("keydown",function(a){"q"===String.fromCharCode(a.which).toLowerCase()&&a.altKey&&(a.preventDefault(),b())});a.addEventListener("click",function(a){a.ctrlKey&&(a.preventDefault(),b())})},setDupChr:function(a){a.addEventListener("keydown",
function(b){if("d"===String.fromCharCode(b.which).toLowerCase()&&b.altKey){b.preventDefault();var e;b=a.value;var d=a.selectionStart,f=a.selectionEnd,g=0;for(e=d-1;0<e&&(g+=1,10!==b.charCodeAt(e));--e);for(;0<e&&(--e,10!==b.charCodeAt(e)););10!==b.charCodeAt(e)&&--g;e=b.charAt(e+g);a.value=b.slice(0,d)+e+b.slice(f);a.selectionStart=d+1;a.selectionEnd=d+1}})},setZen:function(a){function b(d){var f,b,c,h,k,l;c=a.selectionStart;h=a.selectionEnd;k=a.value;l=k.slice(c,h);f=k.slice(0,c);b=k.slice(h);c===
h?alert("nothing selected"):(0===d?e=c=prompt("Enter tag abbreviation\n or command"):c=e,null!==c&&""!==c&&("/*"===c?(d="/* ",c=" */"):"<!"===c?(d="\x3c!-- ",c=" --\x3e"):"ucase"===c?(c=d="",l=l.toUpperCase()):"lcase"===c?(c=d="",l=l.toLowerCase()):'"'===c?c=d='"':"'"===c?c=d="'":(d="<"+c+">",c="</"+c+">"),k=f+d+l+c+b,a.value=k,a.selectionEnd=k.length-b.length,a.selectionStart=k.length-b.length))}var e="";a.addEventListener("keydown",function(d){if("z"===String.fromCharCode(d.which).toLowerCase()&&
d.altKey){a:{var b,e,c,h,k;h=a.selectionStart;c=a.selectionEnd;b=a.value;k=b.slice(h,c);if(""===k){for(;c<b.length&&!(49>b.charCodeAt(c));)c+=1;for(;0<h;)if(--h,49>b.charCodeAt(h)){h+=1;break}k=b.slice(h,c)}if(""===k)alert("No Key Word to Match");else{e=b.slice(0,h);c=b.slice(c);for(b=0;b<atags.length;b+=1)if(k===atags[b].tag){b=e+atags[b].tagx+c;h=b.indexOf("^",h);-1===h?(a.value=b,a.selectionEnd=b.length-c.length,a.selectionStart=b.length-c.length):(e=b.slice(0,h),c=b.slice(h+1),b=e+c,a.value=b,
a.selectionEnd=h,a.selectionStart=h);break a}b=e+"<"+k+"></"+k+">"+c;h=b.indexOf("><",h);h+=1;a.value=b;a.selectionEnd=h;a.selectionStart=h}}d.preventDefault()}});a.addEventListener("keydown",function(a){"a"===String.fromCharCode(a.which).toLowerCase()&&a.altKey&&(b(0),a.preventDefault())});a.addEventListener("keydown",function(a){"w"===String.fromCharCode(a.which).toLowerCase()&&a.altKey&&(b(1),a.preventDefault())})},setLineNbr:function(a){var b="",e;a.addEventListener("keydown",function(d){if("n"===
String.fromCharCode(d.which).toLowerCase()&&d.altKey)if(d.preventDefault(),""===b){e="1\t\t";d=2;var f,g,c,h=a.value;b=h;for(f=0;f<h.length-1;f+=1)if(g=h.charAt(f),"\n"===g){for(c=d.toString();4>c.length;)c+=" ";e+=g+c+"\t\t";d+=1}else e+=g;a.value=e;a.readOnly=!0}else a.readOnly=!1,a.value=b,b=""})}};
Pta.findr={findText:function(a,b){if(2!==arguments.length)alert("missing arguments for findText");else{var e=document.getElementById(a),d=document.getElementById(b),f;f=d.value.length;var g=e.selectionEnd,d=e.value.indexOf(d.value,g);f=d+f;0<=d?(e.selectionStart=d,e.selectionEnd=f,e.focus()):0<g&&(e.selectionStart=0,e.selectionEnd=0,Pta.findr.findText(a,b))}},replaceOne:function(a,b,e){if(3!==arguments.length)alert("missing arguments for findText");else{var d=document.getElementById(a),f=document.getElementById(e);
Pta.findr.findText(a,b);var g,c,h;h=d.value;g=d.selectionStart;c=d.selectionEnd;g===c?alert("No More to replace"):(g=h.slice(0,g),c=h.slice(c),h=g+f.value+c,d.value=h,d.selectionStart=h.length-c.length,d.selectionEnd=h.length-c.length,d.focus())}},replaceAll:function(a,b,e){if(3!==arguments.length)alert("missing arguments for findText");else{var d=document.getElementById(a),f=document.getElementById(b),g=document.getElementById(e),c=d.value,c=c.replace(new RegExp(f.value,"g"),g.value);d.value=c;d.focus()}}};
Pta.insClip=function(a,b){var e=document.getElementById(a),d=e.value,f=e.selectionStart,g=d.slice(0,f),d=d.slice(f);e.value=g+b+d;e.selectionEnd=f+b.length;e.focus()};
