var Pta=Pta||{};
Pta.listeners={initialize:function(a){a=document.getElementById(a);Pta.listeners.setKeys(a);Pta.listeners.setTabs(a);a.style.tabSize=4;Pta.listeners.setIndent(a);Pta.listeners.setJoinLines(a);Pta.listeners.setMatching(a);Pta.listeners.setDupChr(a);Pta.listeners.setZen(a);Pta.listeners.setLineNbr(a)},setKeys:function(a){function b(b){var f=a.value,e=a.selectionStart,g=f.slice(0,e),f=f.slice(e);a.value=g+b+f;a.selectionEnd=e+b.length;a.focus()}a.addEventListener("keydown",function(a){13===a.keyCode&&
a.altKey?(a.preventDefault(),b("<br>")):32===a.keyCode&&a.ctrlKey?(a.preventDefault(),b("&nbsp;")):"c"===String.fromCharCode(a.which).toLowerCase()&&a.altKey&&(a.preventDefault(),b("\x3c!--\t--\x3e"))})},setTabs:function(a){a.addEventListener("keydown",function(b){if(9===b.keyCode&&!b.shiftKey){b.preventDefault();var d,f,e=a.selectionStart,g=a.selectionEnd;f=a.value;if(e===g)a.value=f.slice(0,e)+"\t"+f.slice(g),a.selectionStart=e+1,a.selectionEnd=e+1;else{b=f.slice(e,g);var c;d=b;var h=0;for(c=0;c<
d.length;c+=1)"\n"===d.charAt(c)&&(h+=1);c=h;if(10!==f.charCodeAt(g-1))for(d=b.length;;){c=a.selectionEnd;e=f.indexOf(b,c);g=e+d;if(0<=e)a.selectionStart=e,a.selectionEnd=g;else if(0<c){a.selectionStart=0;a.selectionEnd=0;continue}return}b=b.replace(/\s+$/g,"");b=b.replace(RegExp("\n","g"),"\n\t");d=f.slice(0,e);f=f.slice(g);a.value=d+"\t"+b+"\n"+f;a.selectionStart=e;a.selectionEnd=g+c}}});a.addEventListener("keydown",function(b){if(9===b.keyCode&&b.shiftKey){b.preventDefault();var d,f;b=a.selectionStart;
var e=a.selectionEnd;f=a.value;if(b===e)d=f.slice(0,b-1),f=f.slice(b),a.value=d+f,a.selectionStart=b-1,a.selectionEnd=b-1;else{var g=f.slice(b,e),c;d=g;var h=0;for(c=0;c<d.length;c+=1)"\n"===d.charAt(c)&&(h+=1);c=h;32<g.charCodeAt(0)||(g=g.replace(RegExp("\n\t","g"),"\n"),d=f.slice(0,b),f=f.slice(e),a.value=d+g.slice(1)+f,a.selectionStart=b,a.selectionEnd=e-c)}}})},setJoinLines:function(a){a.addEventListener("keydown",function(b){if("j"===String.fromCharCode(b.which).toLowerCase()&&b.altKey){b.preventDefault();
var d,f=a.selectionStart;d=a.selectionEnd;var e=a.value,g=e.slice(f,d);""===g?alert("No Lines Selected to Join"):(b=e.slice(0,f),d=e.slice(d),g=g.replace(/\n/g,""),a.value=b+g+d,a.selectionEnd=f)}})},setIndent:function(a){a.addEventListener("keydown",function(b){if(13===b.keyCode&&!b.ctrlKey){b.preventDefault();var d,f,e=a.value,g=a.selectionStart,c=a.selectionEnd;for(b=g-1;0<b&&10!==e.charCodeAt(b);--b);d=String.fromCharCode(10);0<b&&(b+=1);for(f=e.charCodeAt(b);32===f||9===f;)d+=String.fromCharCode(f),
b+=1,f=e.charCodeAt(b);a.value=e.slice(0,g)+d+e.slice(c);a.selectionStart=g+d.length;a.selectionEnd=g+d.length}})},setMatching:function(a){function b(){var e=a.value,b=a.selectionStart,c=e.charAt(b);if(0>"{(".indexOf(c)&&(--b,c=e.charAt(b),0>"})".indexOf(c)))return;"}"===c?d("}","{",b):"{"===c?f("{","}",b):")"===c?d(")","(",b):"("===c&&f("(",")",b)}function d(b,f,c){var d,k=0,l=a.value;for(--c;0<=c;--c)if(d=l.charAt(c),d===f)if(0===k){a.selectionStart=c;break}else--k;else d===b&&(k+=1);0>c&&alert("Match not found")}
function f(b,f,c){var d,k,l=0,m=a.value;k=m.length;for(c+=1;c<k;c+=1)if(d=m.charAt(c),d===f)if(0===l){a.selectionEnd=c+1;break}else--l;else d===b&&(l+=1);c>=k&&alert("Match not found")}a.addEventListener("keydown",function(a){"q"===String.fromCharCode(a.which).toLowerCase()&&a.altKey&&(a.preventDefault(),b())});a.addEventListener("click",function(a){a.ctrlKey&&(a.preventDefault(),b())})},setDupChr:function(a){a.addEventListener("keydown",function(b){if("d"===String.fromCharCode(b.which).toLowerCase()&&
b.altKey){b.preventDefault();var d;b=a.value;var f=a.selectionStart,e=a.selectionEnd,g=0;for(d=f-1;0<d&&(g+=1,10!==b.charCodeAt(d));--d);for(;0<d&&(--d,10!==b.charCodeAt(d)););10!==b.charCodeAt(d)&&--g;d=b.charAt(d+g);a.value=b.slice(0,f)+d+b.slice(e);a.selectionStart=f+1;a.selectionEnd=f+1}})},setZen:function(a){function b(b){var e,g,c;c=a.selectionStart;var h=a.selectionEnd,k=a.value,l=k.slice(c,h);e=k.slice(0,c);g=k.slice(h);c===h?alert("nothing selected"):(0===b?d=c=prompt("Enter tag abbreviation"):
c=d,null!==c&&""!==c&&("/*"===c?(b="/* ",c=" */"):"<!"===c?(b="\x3c!-- ",c=" --\x3e"):(b="<"+c+">",c="</"+c+">"),k=e+b+l+c+g,a.value=k,a.selectionEnd=k.length-g.length,a.selectionStart=k.length-g.length))}var d="";a.addEventListener("keydown",function(b){if("z"===String.fromCharCode(b.which).toLowerCase()&&b.altKey){a:{var e,d,c,h=a.selectionStart;c=a.selectionEnd;e=a.value;var k=e.slice(h,c);d=0;if(""===k){for(;c<e.length&&!(49>e.charCodeAt(c));)c+=1;for(;0<h;)if(--h,49>e.charCodeAt(h)){h+=1;break}k=
e.slice(h,c)}if(""===k)alert("No Key Word to Match");else{d=e.slice(0,h);c=e.slice(c);for(e=0;e<atags.length;e+=1)if(k===atags[e].tag){e=d+atags[e].tagx+c;d=e.indexOf("^",h);-1===d?(a.value=e,a.selectionEnd=e.length-c.length,a.selectionStart=e.length-c.length):(a.value=e.replace(/\^/,""),a.selectionEnd=d,a.selectionStart=d);break a}e=d+"<"+k+"></"+k+">"+c;d=e.indexOf("><",h);d+=1;a.value=e;a.selectionEnd=d;a.selectionStart=d}}b.preventDefault()}});a.addEventListener("keydown",function(a){"a"===String.fromCharCode(a.which).toLowerCase()&&
a.altKey&&(b(0),a.preventDefault())});a.addEventListener("keydown",function(a){"w"===String.fromCharCode(a.which).toLowerCase()&&a.altKey&&(b(1),a.preventDefault())})},setLineNbr:function(a){var b="",d;a.addEventListener("keydown",function(f){if("l"===String.fromCharCode(f.which).toLowerCase()&&f.altKey)if(f.preventDefault(),""===b){d="1\t\t";f=2;var e,g,c,h=a.value;b=h;for(e=0;e<h.length-1;e+=1)if(g=h.charAt(e),"\n"===g){for(c=f.toString();4>c.length;)c+=" ";d+=g+c+"\t\t";f+=1}else d+=g;a.value=
d;a.readOnly=!0}else a.readOnly=!1,a.value=b,b=""})}};
Pta.findr={findText:function(a,b){if(2!==arguments.length)alert("missing arguments for findText");else{var d=document.getElementById(a),f=document.getElementById(b),e;e=f.value.length;var g=d.selectionEnd,f=d.value.indexOf(f.value,g);e=f+e;0<=f?(d.selectionStart=f,d.selectionEnd=e):0<g&&(d.selectionStart=0,d.selectionEnd=0,Pta.findr.findText(a,b))}},replaceOne:function(a,b,d){if(3!==arguments.length)alert("missing arguments for findText");else{var f=document.getElementById(a),e=document.getElementById(d);
Pta.findr.findText(a,b);var g,c,h=f.value;g=f.selectionStart;c=f.selectionEnd;g===c?alert("No More to replace"):(g=h.slice(0,g),c=h.slice(c),h=g+e.value+c,f.value=h,f.selectionStart=h.length-c.length,f.selectionEnd=h.length-c.length,f.focus())}},replaceAll:function(a,b,d){if(3!==arguments.length)alert("missing arguments for findText");else{var f=document.getElementById(a),e=document.getElementById(b),g=document.getElementById(d),c=f.value,c=c.replace(new RegExp(e.value,"g"),g.value);f.value=c;f.focus()}}};
