var Pta=Pta||{};
Pta.listeners={initialize:function(a){a=document.getElementById(a);Pta.listeners.setKeys(a);Pta.listeners.setTabs(a);a.style.tabSize=4;Pta.listeners.setIndent(a);Pta.listeners.setJoinLines(a);Pta.listeners.setMatching(a);Pta.listeners.setDupChr(a);Pta.listeners.setZen(a);Pta.listeners.setLineNbr(a)},setKeys:function(a){function b(c){var d=a.value,g=a.selectionStart,e=d.slice(0,g),d=d.slice(g);a.value=e+c+d;a.selectionEnd=g+c.length;a.focus()}a.addEventListener("keydown",function(c){if(13===c.keyCode&&
c.altKey)c.preventDefault(),b("<br>");else if(32===c.keyCode&&c.ctrlKey)c.preventDefault(),b("&nbsp;");else if("c"===String.fromCharCode(c.which).toLowerCase()&&c.altKey)c.preventDefault(),b("\x3c!--\t--\x3e");else if(""!==a.value){c="";var d;for(d=0;d<a.style.tabSize;d+=1)c+=" ";c=a.value.replace(new RegExp(c,"g"),"\t");a.value=c}})},setTabs:function(a){a.addEventListener("keydown",function(b){if(9===b.keyCode&&!b.shiftKey){b.preventDefault();var c,d,g=a.selectionStart,e=a.selectionEnd;d=a.value;
if(g===e)a.value=d.slice(0,g)+"\t"+d.slice(e),a.selectionStart=g+1,a.selectionEnd=g+1;else{b=d.slice(g,e);var f;c=b;var h=0;for(f=0;f<c.length;f+=1)"\n"===c.charAt(f)&&(h+=1);f=h;if(10!==d.charCodeAt(e-1))for(c=b.length;;){f=a.selectionEnd;g=d.indexOf(b,f);e=g+c;if(0<=g)a.selectionStart=g,a.selectionEnd=e;else if(0<f){a.selectionStart=0;a.selectionEnd=0;continue}return}b=b.replace(/\s+$/g,"");b=b.replace(RegExp("\n","g"),"\n\t");c=d.slice(0,g);d=d.slice(e);a.value=c+"\t"+b+"\n"+d;a.selectionStart=
g;a.selectionEnd=e+f}}});a.addEventListener("keydown",function(b){if(9===b.keyCode&&b.shiftKey){b.preventDefault();var c,d;b=a.selectionStart;var g=a.selectionEnd;d=a.value;if(b===g)c=d.slice(0,b-1),d=d.slice(b),a.value=c+d,a.selectionStart=b-1,a.selectionEnd=b-1;else{var e=d.slice(b,g),f;c=e;var h=0;for(f=0;f<c.length;f+=1)"\n"===c.charAt(f)&&(h+=1);f=h;32<e.charCodeAt(0)||(e=e.replace(RegExp("\n\t","g"),"\n"),c=d.slice(0,b),d=d.slice(g),a.value=c+e.slice(1)+d,a.selectionStart=b,a.selectionEnd=g-
f)}}})},setJoinLines:function(a){a.addEventListener("keydown",function(b){if("j"===String.fromCharCode(b.which).toLowerCase()&&b.altKey){b.preventDefault();var c,d=a.selectionStart;c=a.selectionEnd;var g=a.value,e=g.slice(d,c);""===e?alert("No Lines Selected to Join"):(b=g.slice(0,d),c=g.slice(c),e=e.replace(/\n/g,""),a.value=b+e+c,a.selectionEnd=d)}})},setIndent:function(a){a.addEventListener("keydown",function(b){if(13===b.keyCode&&!b.ctrlKey){b.preventDefault();var c,d,g=a.value,e=a.selectionStart,
f=a.selectionEnd;for(b=e-1;0<b&&10!==g.charCodeAt(b);--b);c=String.fromCharCode(10);0<b&&(b+=1);for(d=g.charCodeAt(b);32===d||9===d;)c+=String.fromCharCode(d),b+=1,d=g.charCodeAt(b);a.value=g.slice(0,e)+c+g.slice(f);a.selectionStart=e+c.length;a.selectionEnd=e+c.length}})},setMatching:function(a){function b(d,g,e){var c,b=0,k=a.value;for(--e;0<=e;--e)if(c=k.charAt(e),c===g)if(0===b){a.selectionStart=e;break}else--b;else c===d&&(b+=1);0>e&&alert("Match not found")}function c(d,c,e){var b,h,k=0,l=a.value;
h=l.length;for(e+=1;e<h;e+=1)if(b=l.charAt(e),b===c)if(0===k){a.selectionEnd=e+1;break}else--k;else b===d&&(k+=1);e>=h&&alert("Match not found")}a.addEventListener("keydown",function(d){if("q"===String.fromCharCode(d.which).toLowerCase()&&d.altKey)a:{d.preventDefault(),d=a.value;var g=a.selectionStart,e=d.charAt(g);if(0>"{(".indexOf(e)&&(--g,e=d.charAt(g),0>"})".indexOf(e)))break a;"}"===e?b("}","{",g):"{"===e?c("{","}",g):")"===e?b(")","(",g):"("===e&&c("(",")",g)}})},setDupChr:function(a){a.addEventListener("keydown",
function(b){if("d"===String.fromCharCode(b.which).toLowerCase()&&b.altKey){b.preventDefault();var c;b=a.value;var d=a.selectionStart,g=a.selectionEnd,e=0;for(c=d-1;0<c&&(e+=1,10!==b.charCodeAt(c));--c);for(;0<c&&(--c,10!==b.charCodeAt(c)););10!==b.charCodeAt(c)&&--e;c=b.charAt(c+e);a.value=b.slice(0,d)+c+b.slice(g);a.selectionStart=d+1;a.selectionEnd=d+1}})},setZen:function(a){function b(d){var b,e,f;f=a.selectionStart;var h=a.selectionEnd,k=a.value,l=k.slice(f,h);b=k.slice(0,f);e=k.slice(h);f===
h?alert("nothing selected"):(0===d?c=f=prompt("Enter tag abbreviation"):f=c,null!==f&&""!==f&&("/*"===f?(d="/* ",f=" */"):"<!"===f?(d="\x3c!-- ",f=" --\x3e"):(d="<"+f+">",f="</"+f+">"),k=b+d+l+f+e,a.value=k,a.selectionEnd=k.length-e.length,a.selectionStart=k.length-e.length))}var c="";a.addEventListener("keydown",function(d){if("z"===String.fromCharCode(d.which).toLowerCase()&&d.altKey){a:{var b,c,f;c=a.selectionStart;f=a.selectionEnd;b=a.value;var h=b.slice(c,f);debugger;if(""===h){for(;f<b.length&&
!(65>b.charCodeAt(f));)f+=1;for(;0<c;)if(--c,65>b.charCodeAt(c)){c+=1;break}h=b.slice(c,f)}if(""===h)alert("No Key Word to Match");else{c=b.slice(0,c);f=b.slice(f);for(b=0;b<atags.length;b+=1)if(h===atags[b].tag){b=c+atags[b].tagx+f;a.value=b;a.selectionEnd=b.length-f.length;a.selectionStart=b.length-f.length;break a}b=c+"<"+h+"></"+h+">"+f;a.value=b;a.selectionEnd=b.length-f.length;a.selectionStart=b.length-f.length}}d.preventDefault()}});a.addEventListener("keydown",function(a){"a"===String.fromCharCode(a.which).toLowerCase()&&
a.altKey&&(b(0),a.preventDefault())});a.addEventListener("keydown",function(a){"w"===String.fromCharCode(a.which).toLowerCase()&&a.altKey&&(b(1),a.preventDefault())})},setLineNbr:function(a){var b="",c;a.addEventListener("keydown",function(d){if("l"===String.fromCharCode(d.which).toLowerCase()&&d.altKey){d.preventDefault();if(""===b){c="1\t\t";d=2;var g,e,f,h=a.value;b=h;for(g=0;g<h.length-1;g+=1)if(e=h.charAt(g),"\n"===e){for(f=d.toString();4>f.length;)f+=" ";c+=e+f+"\t\t";d+=1}else c+=e}else c=
b,b="";a.value=c}})}};
Pta.findr={findText:function(a,b){if(2!==arguments.length)alert("missing arguments for findText");else{var c=document.getElementById(a),d=document.getElementById(b),g;g=d.value.length;var e=c.selectionEnd,d=c.value.indexOf(d.value,e);g=d+g;0<=d?(c.selectionStart=d,c.selectionEnd=g):0<e&&(c.selectionStart=0,c.selectionEnd=0,Pta.findr.findText(a,b))}},replaceOne:function(a,b,c){if(3!==arguments.length)alert("missing arguments for findText");else{var d=document.getElementById(a),g=document.getElementById(c);
Pta.findr.findText(a,b);var e,f,h=d.value;e=d.selectionStart;f=d.selectionEnd;e===f?alert("No More to replace"):(e=h.slice(0,e),f=h.slice(f),h=e+g.value+f,d.value=h,d.selectionStart=h.length-f.length,d.selectionEnd=h.length-f.length,d.focus())}},replaceAll:function(a,b,c){if(3!==arguments.length)alert("missing arguments for findText");else{var d=document.getElementById(a),g=document.getElementById(b),e=document.getElementById(c),f=d.value,f=f.replace(new RegExp(g.value,"g"),e.value);d.value=f;d.focus()}}};